### ISSUE TITLE
GitHub Action to publish

### ISSUE THREAD

**Issue by etho201** [coretechonomy/docs#1]
```yaml
name: Publish

on:
  workflow_dispatch:
  push:
    branches: master
  schedule: 
    - cron: '0 20 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }} # Required due to: https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
        
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_PAT }}

    - name: Push to gh-pages branch
      run: |
        export BUILDDIR=build

        mv .git ${BUILDDIR}
        cd ${BUILDDIR}
        git config user.name github-actions
        git config user.email "ethomsen86@gmail.com"
        git add .
        git commit -m "publish"
        git push --quiet --force origin HEAD:gh-pages
```
